version: "3.8"

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    image: alchemy-backend:latest 
    container_name: alchemy_backend_container 
    ports:
      - "8080:8080" 
    restart: unless-stopped 
    networks:
      - alchemy-network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
      args:
        API_URL: https://cozy-contentment-production-7b75.up.railway.app 
    image: alchemy-frontend:latest 
    container_name: alchemy_frontend_container
    ports:
      - "3000:80" 
    depends_on:
      - backend 
    restart: unless-stopped
    networks:
      - alchemy-network


networks:
  alchemy-network:
    driver: bridge
